volumes:
  postgres-data:

services:
  db:
    image: postgres:13.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=bohdan
      - POSTGRES_DB=personal-music
      - ALLOW_IP_RANGE=0.0.0.0/0